# GitHub action to embed code snippets in markdown files.
name: markdown-autodocs

on:
  push:
    branches:
      - master

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
      - name: Downgrade doctoc version
        # Latest version of doctoc uses ES Module format, and conflicts with some packages in markdown-autodocs.
        run: |
          npm install -g doctoc@2.1.0
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
