# GitHub action to embed code snippets in markdown files and update documentation for Lua programs.
name: update-files

on:
  push:
    branches:
      - master

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Run markdown-autodocs to update README.md files.
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
      - name: Downgrade doctoc version
        # Latest version of doctoc uses ES Module format, and conflicts with some packages in markdown-autodocs.
        run: |
          npm install -g doctoc@2.1.0
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: 'markdown-autodocs: Update README.md files'
          # Optional output file paths, defaults to '[./README.md]'.
          output_file_paths: '[**/README.md]'
          # Categories to automatically sync or transform its contents in the markdown files.
          # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
          categories: '[code-block]'
      - name: Cleanup temporary files
        run: |
          rm -f action.py

      # Run simple_doc to update documentation.
      - name: Install Lua
        run: |
          sudo apt-get install -y lua5.3
      - name: Update documentation
        run: |
          cd simple_doc
          ./build_docs.sh
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: 'simple_doc: Update documentation'
